### PR TITLE
Add basic build CI

### PR DESCRIPTION
**Pull request by robtaylor**
taking cue from YoWASP/vscode, add basic CI for build and package

### CODE REVIEW

**Comment by robtaylor** [comment]
as CI isn't currently enabled for forks, here's the run for reference: https://github.com/robtaylor/rtl-debugger-ci/pull/1

**Comment by whitequark** [comment]
I set up continuous integration in https://github.com/amaranth-lang/rtl-debugger/commit/2046b76db5c9a5dd9f089249e4c58c0df7842a3c, and also modernized all of the tooling.



> as CI isn't currently enabled for forks, here's the run for reference: [robtaylor/rtl-debugger-ci#1](https://github.com/robtaylor/rtl-debugger-ci/pull/1)

Enabling CI for forks is something you can/should do on your own. I cannot do it for you.

**Comment by robtaylor** [comment]
> I set up continuous integration in [2046b76](https://github.com/amaranth-lang/rtl-debugger/commit/2046b76db5c9a5dd9f089249e4c58c0df7842a3c), and also modernized all of the tooling.
> 
> > as CI isn't currently enabled for forks, here's the run for reference: [robtaylor/rtl-debugger-ci#1](https://github.com/robtaylor/rtl-debugger-ci/pull/1)
> 
> Enabling CI for forks is something you can/should do on your own. I cannot do it for you.

https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by robtaylor** [comment]
> > I set up continuous integration in [2046b76](https://github.com/amaranth-lang/rtl-debugger/commit/2046b76db5c9a5dd9f089249e4c58c0df7842a3c), and also modernized all of the tooling.
> > > as CI isn't currently enabled for forks, here's the run for reference: [robtaylor/rtl-debugger-ci#1](https://github.com/robtaylor/rtl-debugger-ci/pull/1)
> > 
> > 
> > Enabling CI for forks is something you can/should do on your own. I cannot do it for you.
> 
> https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks

but its working now, so all good...

**Pull request closed without merging**
